image: ruby:2.4

services:
  - postgresql:9.6

before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install
  - rails -v

test:
  script:
    - bundle exec rake test
