# image: ruby:2.4

services:
  - postgres:9.6

variables:
  GIT_SSL_NO_VERIFY: 1
  TEST_HOST: postgres
  POSTGRES_USER: harishramachandran
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: portfolio_test

before_script:
  - ruby -v
  - gem install bundler --no-ri --no-rdoc
  - bundle install
  - rails -v

test:
  script:
    - bundle exec rake test
    - bundle exec rake cucumber
