# image: ruby:2.4

services:
  - postgres:9.6

variables:
  TEST_HOST: postgres
  POSTGRES_USER: harishramachandran
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: portfolio_test

before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install
  - rails -v

test:
  script:
    - bundle exec rake test
    - bundle exec rake cucumber
