# image: ruby:2.4

stages:
  - testing
  - staging
  - production

services:
  - postgres:9.6

variables:
  GIT_SSL_NO_VERIFY: '1'
  TEST_HOST: postgres
  POSTGRES_USER: harishramachandran
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: portfolio_test
  HEROKU_STAGING_APP_NAME: harish-blog-staging
  HEROKU_PROD_APP_NAME: harish-blog

before_script:
  - ruby -v
  - gem install bundler --no-ri --no-rdoc
  - bundle install
  - rails -v

test:
  stage: testing
  script:
    - bundle exec rake test
    - bundle exec rake cucumber

staging_deployment:
  stage: staging
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP_NAME --api-key=$HEROKU_API_KEY
    - "curl -n -X POST https://api.heroku.com/apps/$HEROKU_STAGING_APP_NAME/ps -H \"Accept: application/json\" -H \"Authorization: Bearer ${HEROKU_API_KEY}\" -d \"command=bundle exec rails db:migrate\""
    - "curl -n -X POST https://api.heroku.com/apps/$HEROKU_STAGING_APP_NAME/ps -H \"Accept: application/json\" -H \"Authorization: Bearer ${HEROKU_API_KEY}\" -d \"command=bundle exec rails webpacker:install\""

production_deployment:
  stage: production
  only: 
    - master
  script:
    - gem install dpl
    - dpl --provider=heroku --app=harish-blog --api-key=$HEROKU_API_KEY
    - "curl -n -X POST https://api.heroku.com/apps/$HEROKU_PROD_APP_NAME/ps -H \"Accept: application/json\" -H \"Authorization: Bearer ${HEROKU_API_KEY}\" -d \"command=bundle exec rails db:migrate\""
