# image: ruby:2.4

stages:
  - testing
  - staging
  - production

services:
  - postgres:9.6

variables:
  GIT_SSL_NO_VERIFY: '1'
  TEST_HOST: postgres
  POSTGRES_USER: harishramachandran
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: portfolio_test

before_script:
  - ruby -v
  - gem install bundler --no-ri --no-rdoc
  - bundle install
  - rails -v

test:
  stage: testing
  script:
    - bundle exec rake test
    - bundle exec rake cucumber

staging_deployment:
  stage: staging
  script:
    - gem install dpl
    - dpl --provider=heroku --app=harish-blog-staging --api-key=$HEROKU_API_KEY
    - bundle exec rake db:migrate

production_deployment:
  stage: production
  only: 
    - master
  script:
    - gem install dpl
    - dpl --provider=heroku --app=harish-blog --api-key=$HEROKU_API_KEY
    - bundle exec rake db:migrate
